### PR TITLE
Two optimizations and a fixed warning

### PR DESCRIPTION
**Pull request by snej**

### CODE REVIEW

**Comment by mnunberg** [comment]
What compiler flags are you using to yield these warnings?

**Comment by snej** [comment]
Looks like `-wconversion` triggers the warning. Without the cast I get:
```
jsonsl/jsonsl.c:1289:48: error: implicit conversion loses integer precision: 'int' to 'uint16_t' (aka 'unsigned short') [-Werror,-Wconversion]
            uint16_t w1 = last_codepoint, w2 = uescval;
                                          ~~   ^~~~~~~
```

**Comment by mnunberg** [comment]
Thanks for the changes!

How much did the optimization actually work?

**Comment by snej** [comment]
Hang on, I'm rebasing to clean up the history and clarify some commit messages...

**Comment by snej** [comment]
I know that the fastparse optimization sped up my overall test by about 5% — that test involves parsing 1.3MB of JSON and re-encoding it as Fleece, and the JSON parse looked like about ⅓ of the runtime. So that's about a 15% speedup to jsonsl?

I don't have figures for the unescape optimization, but again it was a measurable boost to my entire test.

(I'm testing on my Macbook Pro, i.e. 64-bit Core i7.)

**Pull request merged**
