### PR TITLE
Improving the file for make and the one for cmake

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by mnunberg** [comment]
```
       -s  Remove all symbol table and relocation information from the
           executable.
```

Why is this something to be provided by default here?

**Comment by RyDroid** [comment]
The binary is lightweight and you use -O3 that is already not good for debugging.

**Comment by mnunberg** [comment]
I only use `-O3` for non-debug builds. The reason I add O3 is because I've specifically benchmarked it to be quicker like that.

Anyway, you are free to add your flags for personal use. I just don't see how this would be of concern to everyone.

**Comment by RyDroid** [comment]
I removed the `-s` option.

**Comment by mnunberg** [comment]
why is the `dist` target modified? the `rm` is intentional since tar will not overwrite an existing archive.

**Comment by RyDroid** [comment]
``sh
$ touch a b
$ tar czf ex.tar a b
$ ll ex.tar 
-rw-rw-r-- 1 user user 116 août  10 15:37 ex.tar
$ echo 'a' > a
$ tar czf ex.tar a b
$ ll ex.tar 
-rw-rw-r-- 1 user user 130 août  10 15:38 ex.tar``

Are you sure? Is it an exception of the GNU implementation?

**Pull request closed without merging**
